"""Write the effective IAM policy documents to infra/policies/ (one JSON per stack).

    .venv/bin/python infra/export_policies.py

It synthesises the app in-process with skip_docker_build=true and pulls every
AWS::IAM::Role (assume-role document) and AWS::IAM::Policy (inline document) out of the
templates. CloudFormation intrinsics (Ref, Fn::GetAtt) are left as they are: they resolve to
the resource ARNs of that deployment. Re-run after changing any stack; the files are
committed so reviewers can read the permissions without deploying.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import app as infra_app  # noqa: E402
from aws_cdk import App  # noqa: E402


def extract(template: dict) -> dict:
    out: dict = {"roles": {}, "policies": {}}
    for logical, res in (template.get("Resources") or {}).items():
        t = res.get("Type")
        props = res.get("Properties") or {}
        if t == "AWS::IAM::Role":
            out["roles"][logical] = {
                "assume_role_policy": props.get("AssumeRolePolicyDocument"),
                "managed_policies": props.get("ManagedPolicyArns", []),
                "inline_policies": props.get("Policies", []),
            }
        elif t == "AWS::IAM::Policy":
            out["policies"][logical] = {
                "roles": props.get("Roles", []),
                "policy_document": props.get("PolicyDocument"),
            }
    return out


def main() -> int:
    out_dir = HERE / "policies"
    out_dir.mkdir(exist_ok=True)
    app = App(context={"skip_docker_build": "true"})
    infra_app.build(app)
    assembly = app.synth()
    written = []
    for stack in assembly.stacks:
        doc = extract(stack.template)
        if not doc["roles"] and not doc["policies"]:
            continue
        p = out_dir / f"{stack.stack_name}.json"
        p.write_text(json.dumps(doc, indent=2, sort_keys=True) + "\n")
        written.append(p)
    index = [
        "# IAM policies",
        "",
        "Generated by `infra/export_policies.py`; do not edit by hand.",
        "",
    ]
    for p in written:
        d = json.loads(p.read_text())
        index.append(
            f"- `{p.name}`: {len(d['roles'])} role(s), {len(d['policies'])} policy document(s)"
        )
    (out_dir / "README.md").write_text("\n".join(index) + "\n")
    for p in written:
        print(p)
    return 0


if __name__ == "__main__":
    sys.exit(main())
