"""Run the benchmark on a fresh EC2 instance without SSH. One configuration per call.

    python -m bench.ec2 --config c7i.xlarge-stock --bucket <bucket> --price 0.1785
    python -m bench.ec2 --config c8g.xlarge-stock --bucket <bucket> --price <USD/h>
    python -m bench.ec2 --config c8g.xlarge-cool  --bucket <bucket> --price <USD/h incl. COOL> --ami ami-...
    python -m bench.ec2 --config c8g.xlarge-cool --dry-run      # print the plan and user-data only

<bucket> is the deployed storage bucket (`make deploy` prints it as BucketName). Per call:

1. `git archive HEAD` of the files the benchmark needs goes to
   s3://<bucket>/outputs/bench/<run>/src.tar.gz (outputs/ expires after a day).
2. Presigned URLs (GET for the source, PUT for the results and the log) go into the
   instance's user-data, so the instance needs no IAM role, key pair or open port.
3. The instance (Canonical's Ubuntu 24.04 from the public SSM parameter, or the COOL AMI
   given with --ami) installs the pinned requirements, or for COOL everything except the
   OpenCV wheel so that the AMI's own build is the one imported, runs `python -m bench.run`,
   uploads `<label>.json`, `<label>.buildinfo.txt` and its log, and powers off. Shutdown
   behaviour is terminate.
4. This script waits for the result, saves it to bench/results/, and terminates the instance
   whatever happens (errors and Ctrl-C included) unless --keep is given.

Needs credentials that may run and terminate instances, read the public SSM parameters and
write to the bucket (the deploy user can), and a default VPC whose subnets give instances a
public IP. The COOL AMI needs a Marketplace subscription first (see bench/README.md).
Committed code only: uncommitted changes are not part of the archive.
"""

from __future__ import annotations

import argparse
import shlex
import subprocess
import sys
import time
from datetime import UTC, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "bench" / "results"
# what bench.run needs on the instance: the package, the clip generator, the harness, pins
ARCHIVE_PATHS = [
    "steadyframe",
    "synth",
    "bench",
    "pyproject.toml",
    "requirements.lock",
    "README.md",
]
SSM_UBUNTU = "/aws/service/canonical/ubuntu/server/24.04/stable/current/{arch}/hvm/ebs-gp3/ami-id"

CONFIGS = {
    "c7i.xlarge-stock": {"instance_type": "c7i.xlarge", "arch": "amd64", "cool": False},
    "c8g.xlarge-stock": {"instance_type": "c8g.xlarge", "arch": "arm64", "cool": False},
    "c8g.xlarge-cool": {"instance_type": "c8g.xlarge", "arch": "arm64", "cool": True},
}

USER_DATA = """#!/bin/bash
# steadyframe benchmark run {label}; generated by bench/ec2.py
set -uo pipefail
LOG=/var/log/steadyframe-bench.log
exec > >(tee -a "$LOG") 2>&1
put() {{ curl -sS -f -X PUT --upload-file "$1" "$2"; }}
finish() {{ sleep 2; put "$LOG" {log_url} || true; shutdown -h now; }}
trap finish EXIT
set -e
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq python3-venv python3-pip curl >/dev/null
mkdir -p /opt/sf && cd /opt/sf
curl -sS -f -o src.tar.gz {src_url}
tar xzf src.tar.gz
if [ "{cool}" = "1" ]; then
  python3 -c "import cv2; print('AMI OpenCV', cv2.__version__, cv2.__file__)"
  python3 -m venv --system-site-packages .venv
  .venv/bin/pip install -q --upgrade pip
  grep -v -i '^opencv' requirements.lock > /tmp/req.txt
  .venv/bin/pip install -q -r /tmp/req.txt
  if ! .venv/bin/python -c "import cv2" 2>/dev/null; then
    # the AMI's cv2 was built against the system numpy: use that one instead of the pin
    echo "AMI cv2 does not import with the pinned numpy; falling back to the system numpy"
    .venv/bin/pip uninstall -y -q numpy
  fi
else
  python3 -m venv .venv
  .venv/bin/pip install -q --upgrade pip
  .venv/bin/pip install -q -r requirements.lock
fi
.venv/bin/pip install -q -e . --no-deps
.venv/bin/python -c "import cv2, numpy; print('bench uses cv2', cv2.__version__, cv2.__file__, 'numpy', numpy.__version__)"
.venv/bin/python -m bench.run --out /opt/sf/out --label {label} --reps {reps}{price_arg}
put out/{label}.json {json_url}
put out/{label}.buildinfo.txt {buildinfo_url}
"""


def user_data(label: str, cool: bool, reps: int, price: float | None, urls: dict[str, str]) -> str:
    return USER_DATA.format(
        label=shlex.quote(label),
        cool="1" if cool else "0",
        reps=int(reps),
        price_arg=f" --price-per-hour {price}" if price is not None else "",
        **{k: shlex.quote(v) for k, v in urls.items()},
    )


def archive() -> bytes:
    dirty = subprocess.run(
        ["git", "status", "--porcelain", "--", *ARCHIVE_PATHS],
        cwd=ROOT,
        capture_output=True,
        text=True,
    ).stdout.strip()
    if dirty:
        print("warning: uncommitted changes are not benchmarked:\n" + dirty, file=sys.stderr)
    return subprocess.run(
        ["git", "archive", "--format=tar.gz", "HEAD", "--", *ARCHIVE_PATHS],
        cwd=ROOT,
        capture_output=True,
        check=True,
    ).stdout


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--config", required=True, choices=sorted(CONFIGS))
    ap.add_argument("--bucket", help="the deployed storage bucket")
    ap.add_argument("--region", default="us-east-1")
    ap.add_argument("--ami", help="AMI id; required for the COOL config (from the Marketplace)")
    ap.add_argument("--price", type=float, help="on-demand USD/h on the day (+ COOL software)")
    ap.add_argument("--reps", type=int, default=10)
    ap.add_argument("--timeout-min", type=float, default=45)
    ap.add_argument("--keep", action="store_true", help="do not terminate the instance")
    ap.add_argument("--dry-run", action="store_true", help="print the plan; touch nothing")
    a = ap.parse_args(argv)
    cfg = CONFIGS[a.config]
    label = a.config
    if cfg["cool"] and not a.ami and not a.dry_run:
        ap.error("the COOL config needs --ami (the AMI id of the Marketplace listing)")
    if a.price is None:
        print("note: no --price, so USD per video-hour stays empty", file=sys.stderr)
    run = datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ") + "-" + label
    prefix = f"outputs/bench/{run}"
    keys = {
        "src_url": f"{prefix}/src.tar.gz",
        "json_url": f"{prefix}/{label}.json",
        "buildinfo_url": f"{prefix}/{label}.buildinfo.txt",
        "log_url": f"{prefix}/{label}.log",
    }
    if a.dry_run:
        urls = {k: f"https://<presigned>/{v}" for k, v in keys.items()}
        ami = a.ami or f"<ssm:{SSM_UBUNTU.format(arch=cfg['arch'])}>"
        print(f"config {label}: {cfg['instance_type']} ({cfg['arch']}), AMI {ami}")
        print(f"archive: {', '.join(ARCHIVE_PATHS)} at HEAD -> s3://<bucket>/{keys['src_url']}")
        print("user-data:\n" + user_data(label, cfg["cool"], a.reps, a.price, urls))
        return 0
    if not a.bucket:
        ap.error("--bucket is required (the BucketName output of make deploy)")

    import boto3
    from botocore.config import Config
    from botocore.exceptions import ClientError

    s3 = boto3.client("s3", region_name=a.region, config=Config(signature_version="s3v4"))
    ec2 = boto3.client("ec2", region_name=a.region)
    ssm = boto3.client("ssm", region_name=a.region)

    ami = a.ami or ssm.get_parameter(Name=SSM_UBUNTU.format(arch=cfg["arch"]))["Parameter"]["Value"]
    s3.put_object(Bucket=a.bucket, Key=keys["src_url"], Body=archive())

    def presign(op: str, key: str) -> str:
        return s3.generate_presigned_url(
            op, Params={"Bucket": a.bucket, "Key": key}, ExpiresIn=int(a.timeout_min * 60) + 900
        )

    urls = {
        "src_url": presign("get_object", keys["src_url"]),
        **{k: presign("put_object", v) for k, v in keys.items() if k != "src_url"},
    }
    resp = ec2.run_instances(
        ImageId=ami,
        InstanceType=cfg["instance_type"],
        MinCount=1,
        MaxCount=1,
        UserData=user_data(label, cfg["cool"], a.reps, a.price, urls),
        InstanceInitiatedShutdownBehavior="terminate",
        MetadataOptions={"HttpTokens": "required", "HttpEndpoint": "enabled"},
        TagSpecifications=[
            {
                "ResourceType": "instance",
                "Tags": [
                    {"Key": "Name", "Value": f"steadyframe-bench-{label}"},
                    {"Key": "project", "Value": "steadyframe"},
                ],
            }
        ],
    )
    iid = resp["Instances"][0]["InstanceId"]
    print(f"launched {iid} ({cfg['instance_type']}, {ami}); waiting for results under {prefix}/")
    t0 = time.time()
    ok = False
    try:
        while time.time() - t0 < a.timeout_min * 60:
            try:
                s3.head_object(Bucket=a.bucket, Key=keys["json_url"])
                ok = True
                break
            except ClientError:
                pass
            state = ec2.describe_instances(InstanceIds=[iid])["Reservations"][0]["Instances"][0]
            if state["State"]["Name"] in ("shutting-down", "terminated"):
                time.sleep(15)  # the result is uploaded before shutdown; one last look
                try:
                    s3.head_object(Bucket=a.bucket, Key=keys["json_url"])
                    ok = True
                except ClientError:
                    pass
                break
            print(f"  {time.time() - t0:5.0f}s  instance {state['State']['Name']}")
            time.sleep(20)
    finally:
        if not a.keep:
            ec2.terminate_instances(InstanceIds=[iid])
            print(f"terminated {iid}")
    RESULTS.mkdir(parents=True, exist_ok=True)
    log = RESULTS / f"{label}.ec2.log"
    try:
        s3.download_file(a.bucket, keys["log_url"], str(log))
    except Exception:
        log = None
    if not ok:
        print(f"no result after {time.time() - t0:.0f}s", file=sys.stderr)
        if log:
            print("".join(log.read_text().splitlines(keepends=True)[-40:]), file=sys.stderr)
        return 1
    for k in ("json_url", "buildinfo_url"):
        dst = RESULTS / Path(keys[k]).name
        s3.download_file(a.bucket, keys[k], str(dst))
        print(f"saved {dst.relative_to(ROOT)}")
    print("next: python -m bench.compare bench/results/*.json --out bench/results/comparison.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
