"""S3 bucket: uploads/, outputs/, samples/. Private, encrypted, 1-day lifecycle on job data."""

from __future__ import annotations

from pathlib import Path

from aws_cdk import CfnOutput, Duration, RemovalPolicy, Stack
from aws_cdk import aws_s3 as s3
from aws_cdk import aws_s3_deployment as s3deploy
from constructs import Construct


class StorageStack(Stack):
    def __init__(
        self, scope: Construct, id: str, *, samples_dir: Path, web_origin: str = "*", **kw
    ) -> None:
        super().__init__(scope, id, **kw)
        self.bucket = s3.Bucket(
            self,
            "Bucket",
            encryption=s3.BucketEncryption.S3_MANAGED,
            block_public_access=s3.BlockPublicAccess.BLOCK_ALL,
            enforce_ssl=True,
            versioned=False,
            removal_policy=RemovalPolicy.DESTROY,
            auto_delete_objects=True,  # `cdk destroy` must leave nothing billable behind
            lifecycle_rules=[
                s3.LifecycleRule(
                    id="uploads-expire-1d",
                    prefix="uploads/",
                    expiration=Duration.days(1),
                    abort_incomplete_multipart_upload_after=Duration.days(1),
                ),
                s3.LifecycleRule(
                    id="outputs-expire-1d", prefix="outputs/", expiration=Duration.days(1)
                ),
            ],
            cors=[
                # the browser PUTs straight to the presigned URL; the URL is the credential,
                # so the origin can stay "*" until the CloudFront domain is known
                s3.CorsRule(
                    allowed_methods=[s3.HttpMethods.PUT, s3.HttpMethods.GET, s3.HttpMethods.HEAD],
                    allowed_origins=[web_origin or "*"],
                    allowed_headers=["*"],
                    exposed_headers=["ETag"],
                    max_age=3000,
                )
            ],
        )
        # the three demo clips (generated by service/samples.py, never committed)
        s3deploy.BucketDeployment(
            self,
            "Samples",
            sources=[s3deploy.Source.asset(str(samples_dir))],
            destination_bucket=self.bucket,
            destination_key_prefix="samples/",
            prune=False,
            retain_on_delete=False,
            memory_limit=256,
        )
        CfnOutput(self, "BucketName", value=self.bucket.bucket_name)
